FEMALE = True
MALE = False
bigdevil = "美国-水猪"

gender_db = {"惠州-Joe":MALE,
            "广州-5":FEMALE,
            "北京-盛义良":MALE,
            "美国-水猪":MALE,
            "山西—浅笑":FEMALE,
            "南昌-瓶子":FEMALE,
            "苏格兰-DL":MALE,
            "上海-周洵":MALE,
            "London-旌":FEMALE,
            "成都-110":FEMALE,
            "济南~Rong":FEMALE,
            "北京-子杰":MALE,
            "Morpheus":FEMALE,
            "上海-起疯了":MALE,
            "成都-一路小雨":MALE,
            "哈尔滨-Chris":MALE,
            "上海-彼格":FEMALE,
            "上海-Charlotte":FEMALE,
            "唐山-桃妖":FEMALE,
            "潍坊-糯糯":FEMALE,
            "北京-小同学":MALE,
            "北京-冒牌小霸王":FEMALE,
            "北京-苏":FEMALE,
            "深圳-Lauren.L":FEMALE,
            "合肥小胖丁":FEMALE,
            "奥克兰-Helen":FEMALE,
            "上海-JOJO":FEMALE,
            "重庆-Frank":MALE,
            "厦门-纯":FEMALE,
            "上海-deadpool":MALE,
            "北京-Howe":MALE,
            "Serbia-Yuphy":FEMALE,
            "上海-波士顿-Annie":FEMALE,
            "北京-淼淼":FEMALE,
            "泉州―绿子":FEMALE,
            "湖南-玉树麟风":MALE
 }
